In [1]:
import pandas as pd

In [5]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html
df_currency = pd.read_excel('datasets/3/currency_table.xlsx', sheet_name='RC')
df_currency.head()

   nominal       data     curs         cdx
0        1 2017-09-01  58.5454  Доллар США
1        1 2017-09-02  58.0557  Доллар США
2        1 2017-09-05  57.7817  Доллар США
3        1 2017-09-06  57.8503  Доллар США
4        1 2017-09-07  57.3387  Доллар США

In [51]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html
with open('datasets/3/currency_table.xlsx', 'rb') as excel_file:
    excel_content = excel_file.read()
df_currency_2 = pd.read_excel(excel_content)
df_currency_2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nominal  736 non-null    int64
 1   data     736 non-null    datetime64[ns]
 2   curs     736 non-null    float64
 3   cdx      736 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 23.1+ KB

In [56]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
custom_parser = lambda date: pd.datetime.strptime(date, '%d+%m+%Y')
with open('datasets/3/currency_table_broken.csv', 'r') as csv_file:
    df_currency_3 = pd.read_csv(csv_file, sep=';', parse_dates=['data'], date_parser=custom_parser)
df_currency_3
# OR:
# import io 
# df_currency_3 = pd.read_csv(io.StringIO(csv_content))
# df_currency_3
# OR (s3fs needed):
# pd.read_csv('s3://datasets/3/currency_table_broken.csv')

     nominal       data     curs         cdx
0          1 2017-09-01  58,5454  Доллар США
1          1 2017-09-02  58,0557  Доллар США
2          1 2017-09-05  57,7817  Доллар США
3          1 2017-09-06  57,8503  Доллар США
4          1 2017-09-07  57,3387  Доллар США
..       ...        ...      ...         ...
731        1 2020-08-26  74,5126  Доллар США
732        1 2020-08-27  75,5379  Доллар США
733        1 2020-08-28  75,2354  Доллар США
734        1 2020-08-29  74,6382  Доллар США
735        1 2020-09-01  73,8039  Доллар США

[736 rows x 4 columns]

In [92]:
df_google_play = pd.read_csv('datasets/3/googleplaystore_user_reviews.csv')
df_google_play.memory_usage().sum()

2571928

In [97]:
# Large dataset
# https://towardsdatascience.com/why-and-how-to-use-pandas-with-large-data-9594dda2ea4c
df_google_play_chunks = pd.read_csv('datasets/3/googleplaystore_user_reviews.csv', chunksize=10000)
chunks_memory_usage = []
print(f'Iterator:\t{type(df_google_play_chunks)}')
for df_chunk in df_google_play_chunks:
    print(f'Type:\t{type(df_chunk)}')
    memory_usage = df_chunk.memory_usage().sum()
    print(f'Chunk memory usage\t{memory_usage}')
    chunks_memory_usage.append(memory_usage)

print(f'\nResult sum size: {sum(chunks_memory_usage)}')

Iterator:	<class 'pandas.io.parsers.TextFileReader'>
Type:	<class 'pandas.core.frame.DataFrame'>
Chunk memory usage	400128
Type:	<class 'pandas.core.frame.DataFrame'>
Chunk memory usage	400132
Type:	<class 'pandas.core.frame.DataFrame'>
Chunk memory usage	400132
Type:	<class 'pandas.core.frame.DataFrame'>
Chunk memory usage	400132
Type:	<class 'pandas.core.frame.DataFrame'>
Chunk memory usage	400132
Type:	<class 'pandas.core.frame.DataFrame'>
Chunk memory usage	400132
Type:	<class 'pandas.core.frame.DataFrame'>
Chunk memory usage	171932

Result sum size: 2572720

In [ ]:
# https://stackoverflow.com/questions/18885175/read-a-zipped-file-as-a-pandas-dataframe
# https://pandas.pydata.org/pandas-docs/stable/reference/io.html
# charted...